version: '3.8'

services:
  dev:
    container_name: zendesk-coding-challenge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/zendesk-coding-challenge'
      - '/zendesk-coding-challenge/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  test:
    container_name: zendesk-coding-challenge-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/zendesk-coding-challenge'
      - '/zendesk-coding-challenge/node_modules'
    environment:
      - CI=true
    command: npm test
  prod:
    container_name: zendesk-coding-challenge-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'

