export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";

export const UPDATE_SUBSCRIPTION_SUCCESS = "UPDATE_SUBSCRIPTION_SUCCESS";

export const UPDATE_SUBSCRIPTION_FAILURE = "UPDATE_SUBSCRIPTION_FAILURE";

export const GET_CURRENT_SUBSCRIPTION = "GET_CURRENT_SUBSCRIPTION";

export const GET_CURRENT_SUBSCRIPTION_SUCCESS = "GET_CURRENT_SUBSCRIPTION_SUCCESS";

export const GET_CURRENT_SUBSCRIPTION_FAILURE = "GET_CURRENT_SUBSCRIPTION_FAILURE";

export const ASYNC_CALL_STARTED = "ASYNC_CALL_STARTED"

export const GET_PRICE_SUCCESS = "GET_PRICE_SUCCESS"

export const GET_PRICE_FAILURE = "GET_PRICE_FAILURE"

